# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20160119_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='postcomments',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postcomments',
            name='wall_post',
        ),
        migrations.RemoveField(
            model_name='wallpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='wallpost',
            name='posted_to',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='PostComments',
        ),
        migrations.DeleteModel(
            name='WallPost',
        ),
    ]
