# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20160120_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=b'documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='wallpost',
            name='posted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
