# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_auto_20160120_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
